base_path: .
blurb_max: 50
date_format: '%Y-%m-%d'
home_page: index
markdown_exts:
- codehilite
- toc
- pykwiki.ext.tpl
- pykwiki.ext.post
postlist:
  max_pages: 5
  order_field: mtime
  order_type: descending
  per_page: 2
  post_type: preview
rss_max_entries: 20
site:
  author: Evidlo
  base_url: ''
  description: PurdueLUG Wiki
  keywords: example, purdue, wiki
  title: PurdueLUG Wiki
source_ext: .md
style: classic
target_dir: docroot
theme: null
time_format: '%H:%M:%S'
timestamp_format: '%Y-%m-%d %H:%M'
upload_exts:
- .gif
- .jpg
- .jpeg
- .png
- .tiff
- .pdf
version: 2
web_prefix: '/wiki'
